on:
  push:
    branches:
      - production
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    
    # - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      #run: |
        #install -m 600 -D /dev/null ~/.ssh/id_rsa
        #echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        #ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

       # mkdir -p ~/.ssh
       # touch -p ~/.ssh/known_hosts
       # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       # chmod 600 ~/.ssh/id_rsa
       # ssh-keyscan -p 22 ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_testing_github_action_wrunner_mosca
        sudo chmod 600 ~/.ssh/id_rsa_testing_github_action_wrunner_mosca
        echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts

    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.DEPLOY_BRANCH }} && git pull && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        run: npm run build
    - name: Message
      run: echo "Hello complete"
    
